language: java
before_install:
    - sudo apt-get install -y python3-pip
before_deploy:
    # create some env vars
    - PROJ_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
    - ARTIFACTID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
    # install PyGithub
    - sudo pip3 install PyGithub
    # download githubrelease.py
    - wget https://raw.githubusercontent.com/Immueggpain/citools/master/githubrelease.py
    - pwd
deploy:
    provider: script
    script: python3 githubrelease.py "target/$ARTIFACTID-$PROJ_VERSION.zip" "target/$ARTIFACTID-$PROJ_VERSION.jar"
    skip_cleanup: true
    on:
        tags: true
